### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by ta3pks** [chances/sandwiches#4]
![screenshot from 2016-03-02 07-46-15](https://cloud.githubusercontent.com/assets/9097437/13450882/09f8f810-e04b-11e5-842b-d12648cf0c17.png)
i have this makefile and i run sadwiche make test but it wont work
when i try sandwich help i aint work too gives no output under my ubuntu 15.10

**Comment by chances** [comment]
Apologies. This utility is largely a work in progress and is not ready for general use.

**Comment by ta3pks** [comment]
well i am looking forward to it i am using gulp but i love makefiles its so simple to write and they check whether the source is newer then the target etc
